default: &base
  adapter: postgresql
  encoding: unicode
  pool: 2
  host: 127.0.0.1

development:
  <<: *base
  database: coursify_development

test:
  <<: *base
  database: coursify_test

production:
  <<: *base
  database: coursify_production
