setup: &setup
  adapter: postgresql
  username: postgres
  password:
  encoding: unicode

development:
  <<: *setup
  database: rails-examples_development

test:
  <<: *setup
  database: rails-examples_test
  
production:
  <<: *setup
  username: rails-examples
  database: rails-examples_production
