base: &base
  secret_key_base: '<set key>'
  facebook:
    key: '<set key>'
    secret: '<set secret>'
  basic_auth:
    username: '<set username>'
    password: '<set password'
  airbrake:
    api_key: '1234her'

development:
  <<: *base

test: *base
