base: &base
  secret_key_base: '<set key>'

development:
  <<: *base
  facebook:
    key: '<set key>'
    secret: '<set secret>'
  basic_auth:
    username: '<set username>'
    password: '<set password'

test: *base
