base: &base
  secret_key_base: '<set key>'

production:
  <<: *base
  facebook:
    key: '<set key>'
    secret: '<set secret>'
    basic_auth:
      username: '<set username>'
      password: '<set password'

development:
  <<: *base
  facebook:
    key: '<set key>'
    secret: '<set secret>'

test: *base
